### PR TITLE
Remove setting ID after Ford's suggestion

### PR DESCRIPTION
**Pull request by nenadjaja**
Connects to https://github.com/graphprotocol/adchain-subgraph/issues/16
Resolves https://github.com/graphprotocol/adchain-subgraph/issues/16

### CODE REVIEW

**Comment by leodasvacas** [comment]
I'm a bit surprised here, aren't all entities required to set an ID?

**Comment by Jannis** [comment]
@leodasvacas Yes, but we recently merged a new feature: implicitly add the ID that is passed to `store.set()` as the second parameter into the entity. This means you only have to provide the ID once now — when calling `store.set()`.

**Comment by Jannis** [comment]
See https://github.com/graphprotocol/graph-node/commit/1a806f375344483a6596e7368d75427b03dd5e5b for more details.

**Comment by leodasvacas** [comment]
@Jannis didn't notice that was in, lovely!

**Pull request merged**
